#! /bin/sh
sxhkd &
~/.config/polybar/launch_polybar.sh &
feh ~/pictures/wallpaper/* --bg-center &
picom -r 3 -o 1 -l 5 -t 5 -D 6\
	--shadow-red 0.11 --shadow-green 0.12 --shadow-blue 0.13 \
	--vsync --backend glx \
	--no-use-damage --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config top_padding 35
bspc config focused_border_color '#d79921'
bspc config window_gap          	12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Surf state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
