#! /bin/sh


sxhkd &
dunst &
~/.config/polybar/launch_polybar.sh &
feh ~/pictures/wallpaper/gaara.jpg --bg-center -z &
compton --config ~/.config/compton/compton.conf &

for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	bspc monitor $m -d I II III IV V VI VII VIII IX X
done

bspc config border_width			1
bspc config top_padding 			35
bspc config focused_border_color '#d79921'
bspc config window_gap				12
bspc config split_ratio				0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true

bspc rule -a Audio-recorder state=tiled sticky=off
bspc rule -a Surf state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox:Toolkit sticky=on state=floating rectangle=640x360+1250+690
bspc rule -a scratchpad sticky=on hidden=on state=floating follow=on rectangle=1000x150+310+5 border=off monitor=focused

[ "$(ps -x | grep -c 'scratchpad')" -le "1" ] && st -c scratchpad &

# launch kdeconnect if existing
# [ -f "/usr/lib/kdeconnectd" ] && /usr/lib/kdeconnectd &
