#!/bin/bash

volume_values=( 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%)

get_index() {
	current_value="$(light -G)"
	for i in "${!light_values[@]}"
	do
		[ "${light_values[$i]}" = "$current_value" ] \
			&& echo $i
	done
}

current_index=$(get_index)

[ $1 = "-A" ] 
[ $1 = "-U" ]
[ $1 = "-G" ]
