#!/bin/bash 

light_values=(0.05 0.10 0.50 1.00 5.00 10.00 15.00 20.00 25.00 30.00 35.00)

get_index() {
	current_value="$(light -G)"
	for i in "${!light_values[@]}"
	do
		[[ "${light_values[$i]}" = "$current_value" ]] && echo $i
	done
}

current_index=$(get_index)

[[ $1 = "-A" ]] && light -S "${light_values[$((current_index + 1))]}"
[[ $1 = "-U" && "$current_index" > 0 ]] && light -S "${light_values[$((current_index - 1))]}" 

