#!/bin/bash 


[ "$#" -eq 1 ] \
&& wallpaper="$(ls ~/Pictures/wallpapers/*/* | grep -i $1 | shuf -n 1)" 

[ "$#" -eq 0 ] \
&& wallpaper="$(ls ~/Pictures/wallpapers/*/* | shuf -n 1)"

feh --bg-fill "$wallpaper"
echo "$wallpaper"
