#!/bin/bash

[ $1 = "-G" ] && pactl list sinks | grep "^\s*Volume:" | head -1 | cut -d/ -f2 | tr -d [:blank:]  && exit 0

for sink in $(pactl list sinks | grep "Name:" | cut -d: -f2 )
do 
	[ $1 = "-A" ] && pactl set-sink-volume $sink +5%
	[ $1 = "-U" ] && pactl set-sink-volume $sink -5%
	[ $1 = "-S" ] && pactl set-sink-volume $sink $2
done

