#!/bin/bash 
# . "${HOME}/.cache/wal/colors.sh"

colors (){
	fg="$(tail -1 ~/.cache/wal/colors)"
	bg="$(head -1 ~/.cache/wal/colors)"

	echo "bg_i3_a0: ${bg}d9"
	echo "bg_i3_a1: ${bg}77"
	echo "fg_i3_a0: ${fg}d9"
	echo "fg_i3_a1: ${fg}77"

	echo "bg_polybar_a0: #d9p${bg}"
	echo "bg_polybar_a1: #77p${bg}"
	echo "fg_polybar_a0: #d9p${fg}"
	echo "fg_polybar_a1: #77p${fg}"
}

[ "$#" -eq 1 ] \
&& wallpaper="$(ls ~/Pictures/wallpapers/*/* | grep -i $1 | shuf -n 1)" 

[ "$#" -eq 0 ] \
&& wallpaper="$(ls ~/Pictures/wallpapers/*/* | shuf -n 1)"

feh --bg-fill "$wallpaper"

# change the color scheme
wal -e -i "$wallpaper" &> /dev/null
xrdb -merge ~/.cache/wal/colors.Xresources
xrdb -merge <(sed -e "s/p#//" <(colors))

# reload things
i3-msg reload &> /dev/null
~/.config/polybar/launch-polybar.sh &>/dev/null & disown 
pywalfox update &>/dev/null
zathura-pywal -a 0.9 &>/dev/null
# reload_dunst

echo "$wallpaper"
