#!/bin/sh

battery_status=$( acpi | cut -d, -f2 | tr -d "% ")
discharging=$(acpi | cut -d: -f2 | cut -d, -f1 | tr -d " ")
(( battery_status < 20 )) \
	&& [[ "$discharging" == "Discharging" ]] \
	&& notify-send Battery "Battery low $battery_status%"

