#!/bin/bash

colors (){
	bg="$(tail -1 ~/.cache/wal/colors)"
	fg="$(head -1 ~/.cache/wal/colors)"

	echo "bg_i3_a0: ${bg}d9"
	echo "bg_i3_a1: ${bg}77"
	echo "fg_i3_a0: ${fg}d9"
	echo "fg_i3_a1: ${fg}77"

	echo "bg_polybar_a0: #d9p${bg}"
	echo "bg_polybar_a1: #77p${bg}"
	echo "fg_polybar_a0: #d9p${fg}"
	echo "fg_polybar_a1: #77p${fg}"
}

sed -e "s/p#//" <(colors)
