#!/usr/bin/env python
#-*- coding: utf-8 -*-
from os import path
import os
import subprocess
import glob
import stat
from pwd import getpwuid
from optparse import OptionParser


# File extension descriptions.
# Format: "EXTENSION": [u"ICON","COLOR CODE"]
EXTENSIONS = {":FILE":	[u"", "14"],
              ":DIRECTORY":	[u"", "12"],
              "7z":			[u"", "229"],
              "ai":			[u"", "14"],
              "bat":		[u"", "10"],
              "bmp":		[u"", "14"],
              "bz":			[u"", "229"],
              "bz2":		[u"", "229"],
              "c":			[u"", "10"],
              "c++":		[u"", "10"],
              "cc":			[u"", "10"],
              "clj":		[u"", "10"],
              "cljc":		[u"", "10"],
              "cljs":		[u"", "10"],
              "coffee":		[u"", "10"],
              "conf":		[u"", "10"],
              "cp":			[u"", "10"],
              "cpp":		[u"", "10"],
              "css":		[u"", "10"],
              "cxx":		[u"", "10"],
              "d":			[u"", "10"],
              "dart":		[u"", "10"],
              "db":			[u"", "10"],
              "diff":		[u"", "10"],
              "dump":		[u"", "105"],
              "edn":		[u"", "10"],
              "ejs":		[u"", "10"],
              "erl":		[u"", "10"],
              "f#":			[u"", "10"],
              "fish":		[u"", "10"],
              "fs":			[u"", "10"],
              "fsi":		[u"", "10"],
              "fsscript":	[u"", "10"],
              "fsx":		[u"", "10"],
              "gif":		[u"", "14"],
              "go":			[u"", "10"],
              "gz":			[u"", "229"],
              "hbs":		[u"", "10"],
              "hrl":		[u"", "10"],
              "hs":			[u"", "10"],
              "htm":		[u"", "10"],
              "html":		[u"", "10"],
              "ico":		[u"", "14"],
              "ini":		[u"", "10"],
              "java":		[u"", "10"],
              "jl":			[u"", "10"],
              "jpeg":		[u"", "14"],
              "jpg":		[u"", "14"],
              "js":			[u"", "10"],
              "json":		[u"", "10"],
              "jsx":		[u"", "10"],
              "less":		[u"", "10"],
              "lhs":		[u"", "10"],
              "lua":		[u"", "10"],
              "markdown":	[u"", "11"],
              "md":			[u"", "11"],
              "ml":			[u"λ", "10"],
              "mli":		[u"λ", "10"],
              "mustache":	[u"", "10"],
              "php":		[u"", "10"],
              "pl":			[u"", "10"],
              "pm":			[u"", "10"],
              "png":		[u"", "14"],
              "psb":		[u"", "14"],
              "psd":		[u"", "14"],
              "py":			[u"", "10"],
              "pyc":		[u"", "10"],
              "pyd":		[u"", "10"],
              "pyo":		[u"", "10"],
              "rb":			[u"", "10"],
              "rlib":		[u"", "10"],
              "rs":			[u"", "10"],
              "rss":		[u"", "105"],
              "scala":		[u"", "10"],
              "scss":		[u"", "10"],
              "sh":			[u"", "10"],
              "slim":		[u"", "10"],
              "sln":		[u"", "10"],
              "sql":		[u"", "10"],
              "styl":		[u"", "10"],
              "suo":		[u"", "10"],
              "t":			[u"", "105"],
              "tar":		[u"", "229"],
              "ts":			[u"", "14"],
              "twig":		[u"", "10"],
              "txt":		[u"", "3"],
              "vim":		[u"", "10"],
              "xul":		[u"", "10"],
              "xz":			[u"", "229"],
              "yml":		[u"", "10"],
              "zip":		[u"", "229"],
              }

# Formats colors. Makes printing a bit easier.
def colorfmt(c):
    return "\x1b[38;5;%sm" % c

def permissions_to_unix_name(st):
    is_dir = 'd' if stat.S_ISDIR(st.st_mode) else '-'
    dic = {'7': 'rwx', '6': 'rw-', '5': 'r-x', '4': 'r--', '0': '---'}
    perm = str(oct(st.st_mode)[-3:])
    return is_dir + ''.join(dic.get(x, x) for x in perm)

def get_user_name(file_stat):
    try:
        return getpwuid(file_stat.st_uid).pw_name
    except KeyError:
        return ""

def get_file_size(file_stat):
    size = file_stat.st_size
    if size <= 1024:
        return "%d B" % size
    size /= 1024

    if size <= 1024:
        return "%d KB" % size
    size /= 1024

    if size <= 1024:
        return "%d MB" % size
    size /= 1024

    return "%d GB" % size

if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option(
        "-l",
        "--list",
        action="store_true",
        default=False,
     dest="is_list")

    parser.add_option(
        "-a",
        "--all",
        action="store_true",
        default=False,
     dest="is_all")

    (options, args) = parser.parse_args()

    directory = ""
    if len(args) > 0:
        directory = args[0]
        if len(directory) > 0 and directory[-1] != "/":
            directory = directory + "/"

    files = glob.glob(directory + '*')

    if options.is_all:
        files = files + glob.glob(directory  + '.*')

    formattedfiles = []

    for f in sorted(files, key=lambda v: v.upper(),):
        file_line = ''
        file_color = ''
        if path.isfile(f):
            (name, ext) = path.splitext(f)
            ext = ext.replace(".", "")
            if ext in EXTENSIONS:
                file_line = ("%s %s" % (EXTENSIONS[ext][0], f))
                file_color = colorfmt(EXTENSIONS[ext][1])
            if ext not in EXTENSIONS:
                file_line = ("%s %s" % (EXTENSIONS[u":FILE"][0], f))
                file_color = colorfmt(EXTENSIONS[u":FILE"][1])
        else:
            file_line = ("%s %s" % (EXTENSIONS[u":DIRECTORY"][0], f))
            file_color = colorfmt(EXTENSIONS[u":DIRECTORY"][1])
        if options.is_list:
            try:
                file_stat = os.stat(f)
                file_line = u"{:<15}{:<10}{:<10}{}".format(
                                    permissions_to_unix_name(file_stat),
                                    get_user_name(file_stat),
                                    get_file_size(file_stat), file_line)
            except OSError:
                file_line = f
        formattedfiles.append((file_line, file_color))
    fstr = ''
    for f in formattedfiles:
        fstr += f[0]+"\n"

    if not options.is_list:
        # Temporary file because I can't pipe the string to column yet -
        # limitation (hdd speed)
        tmpfile = open("lsfile", "w")
        try:
            # Python 3
            tmpfile.write(fstr)
        except UnicodeEncodeError:
            # Python 2
            tmpfile.write(str(fstr.encode('utf-8')))
        tmpfile.close()
        # Yes, I know I'm using shell=True. One reason why you SHOULD NOT give
        # this program full permissions.
        output = subprocess.check_output(
            "cat lsfile | column -c $(tput cols); rm -rf lsfile",
            shell=True).decode('utf-8')
    else:
        output = fstr

    for f in formattedfiles:
        output = output.replace(f[0], f[1]+f[0])

    print(output.strip('\n'))
