#!/bin/bash

echo COURSES: 
cd ~/courses
git status | head -2

git status -s 


echo 
echo ORGANISATION: 
cd ~/org
git status | head -2

git status -s 

echo 
echo ORGANISATION: 
cd ~/projects/archbox
git status | head -2

git status -s 
