#!/bin/bash

# TEXT='#d79921ee'
# WRONG='#cc241dbb'
# VERIFYING='#98971abb'
# DEFAULT='#d79921cc'

if [ $# = 1 ]
then 
	convert "$1" -blur 0x8 /tmp/login.jpg
	login=("-i" "/tmp/login.jpg")
fi

BLANK='#28282833' #'#00000000'
CLEAR='#282828cc'
DEFAULT="$(xrdb -get color1)ee"
TEXT="$(xrdb -get color1)ee"
WRONG="$(xrdb -get color3)bb"
VERIFYING="$(xrdb -get color2)ff"

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 1                \
"${login[@]}"
