#!/usr/bin/bash

id="$(xdotool search --class scratchpad)" 
[ -z "$id" ] && alacritty --class scratchpad,scratchpad 

id="$(xdotool search --class scratchpad)" 
bspc node "$id" -m focused 
bspc node "$id" --flag hidden -f


