#!/bin/bash

files="$(pdfgrep -i $@ | cut -d: -f1 | uniq)"

while true
do
	# get file with fuzzy search
	file="$(echo "$files" | fzf --preview "pdfgrep -i -C 5 \"$1\" {}")"

	# if empty (you pressed escape) exit out of programm
	[[ -z $file ]] && exit

	# open vim with thing searched and highlighted
	zathura -f "$1" $file
done
